<link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="assets/css/bootstrap-grid.min.css">
<link rel="stylesheet" type="text/css" href="assets/css/bootstrap-reboot.min.css">
<link rel="stylesheet" type="text/css" href="assets/css/datatables.min.css">
<link rel="stylesheet" type="text/css" href="assets/css/jquery-ui.min.css">
<link rel="stylesheet" type="text/css" href="assets/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" type="text/css" href="assets/css/style.css">
<link rel="stylesheet" type="text/css" href="assets/css/fa-brands.min.css">
<link rel="stylesheet" type="text/css" href="assets/css/fa-regular.min.css">
<link rel="stylesheet" type="text/css" href="assets/css/fa-solid.min.css">
<link rel="stylesheet" type="text/css" href="assets/css/fontawesome.min.css">
<link rel="stylesheet" type="text/css" href="assets/css/fontawesome-all.min.css">
<script src="assets/js/jquery.min.js" type="text/javascript" charset="utf-8"></script>
<script src="assets/js/jquery.mask.min.js" type="text/javascript" charset="utf-8"></script>
<script src="assets/js/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
<script src="assets/js/bootstrap.min.js" type="text/javascript" charset="utf-8"></script>
